name: test job

#on: [push, pull_request] # push 和 pull_request 时会触发
on:
  workflow_dispatch:  # 手动触发

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: zfile-pro.exe
            folder_name: zfile-pro-windows-amd64
            compress_name: zfile-pro-windows-amd64.zip
            static: false

          - os: ubuntu-latest
            artifact_name: zfile-pro
            folder_name: zfile-pro-linux-amd64
            compress_name: zfile-pro-linux-amd64.tar.gz
            static: false
    steps:
      - name: Generate File1
        run: echo "hello from ${{ matrix.os }}" > ${{ matrix.compress_name }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zfile-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
          path: ${{ matrix.compress_name }}
  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: zfile-artifacts
          pattern: zfile-*
          merge-multiple: true
      - name: List files
        run: |
          pwd
          ls -lha
          ls -lha zfile-artifacts
          ls -R zfile-artifacts
