name: test job

#on: [push, pull_request] # push 和 pull_request 时会触发
on:
  workflow_dispatch:  # 手动触发
    inputs:
      buildStatic:
        description: 'Build Static File'
        type: boolean
        default: true
        required: false

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: zfile-pro.exe
            folder_name: zfile-pro-windows-amd64
            compress_name: zfile-pro-windows-amd64.zip
            static: false

          - os: ubuntu-latest
            artifact_name: zfile-pro
            folder_name: zfile-pro-linux-amd64
            compress_name: zfile-pro-linux-amd64.tar.gz
            static: false

    steps:
      - name: Generate File1
        run: |
          mkdir -p ${{ matrix.folder_name }}
          echo "Hello World" > ${{ matrix.folder_name }}/${{ matrix.artifact_name }}

      - name: Generate File2
        if: runner.os == 'Windows'
        run: |
          echo "Hello World123" > ${{ matrix.folder_name }}/a.dll
          echo "Hello World345" > ${{ matrix.folder_name }}/b.dll

      - name: Generate File3
        if: runner.os != 'Windows'
        run: |
          echo "HelloWorld123" > ${{ matrix.folder_name }}/a.so
          echo "HelloWorld345" > ${{ matrix.folder_name }}/b.so

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zfile-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
          path: ${{ matrix.folder_name }}

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: zfile-artifacts
          pattern: zfile-*
          merge-multiple: true
      - name: List files
        run: |
          pwd
          ls -lha
          ls -lha zfile-artifacts
          ls -R zfile-artifacts
